version: '3'
services:
  django:
    build:
      context: ./backend # Path to the Django project directory
    ports:
      - 8000:8000
    depends_on:
      - react
      - redis
    networks:
      - app-network

  react:
    build:
      context: ./frontend  # Path to the React project directory
    ports:
      - 3000:3000
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

  celery:
    build:
      context: ./backend  # Path to the Django project directory
    command: celery -A backend worker 
    depends_on:
      - django
      - redis
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - react
      - redis


networks:
  app-network:
    driver: bridge
