version: '3'
services:
  django:
    build:
      context: ./backend
    networks:
      - app-network
  react:
    build:
      context: ./frontend
    networks:
      - app-network
  redis:
    image: redis:latest
    networks:
      - app-network
  celery:
    build:
      context: ./backend
    command: celery -A backend worker -l INFO
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - django
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
