version: '3'
services:
  django:
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build:
      context: ./backend # Path to the Django project directory
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - redis
  react:
    build:
      context: ./frontend  # Path to the React project directory
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - './frontend/src:/frontend/src'
    command: npm start

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
