version: '3'
services:
  django:
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build:
      dockerfile: Dockerfile.prod
      context: ./backend # Path to the Django project directory
      # dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - redis

  react:
    build:
      #dockerfile: Dockerfile.prod
      dockerfile: Dockerfile.dev
      context: ./frontend  # Path to the React project directory
    ports:
      #- 80:80
      #- 443:443
      - 3000:3000
    networks:
      - app-network
    volumes:
      - './frontend/src:/frontend/src'

  redis:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
