# Generated by Django 4.1.6 on 2023-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='color',
            field=models.CharField(default='w', max_length=1),
        ),
    ]
