# Generated by Django 4.1.6 on 2023-05-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0002_chessgame_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='bot_elapsed_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='player_elapsed_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='time_control',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
