# Generated by Django 4.1.6 on 2023-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0003_chessgame_bot_elapsed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatars/basic_avatar.png', upload_to='images/avatars'),
        ),
    ]
