# Generated by Django 4.1.6 on 2023-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/basic_avatar.png', upload_to='images/'),
        ),
    ]
