# Generated by Django 4.1.6 on 2023-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='last_move_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
