# Generated by Django 4.1.6 on 2023-06-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0006_chessgame_last_move_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='bot_elapsed_time',
            new_name='bot_remaining_time',
        ),
        migrations.RenameField(
            model_name='chessgame',
            old_name='player_elapsed_time',
            new_name='player_remaining_time',
        ),
    ]
