# Generated by Django 4.1.6 on 2023-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0007_rename_bot_elapsed_time_chessgame_bot_remaining_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
