# Generated by Django 4.1.6 on 2023-06-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0008_chessgame_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
