# Generated by Django 4.1.6 on 2023-06-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0009_chessgame_is_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
