# Generated by Django 4.1.6 on 2023-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0010_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/basic_avatar.png', upload_to='images/'),
        ),
    ]
