# Generated by Django 4.1.6 on 2023-06-06 13:06

from django.db import migrations, models
import test_.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/basic_avatar.png', upload_to=test_.models.get_image_upload_path),
        ),
    ]
