# Generated by Django 4.1.6 on 2023-06-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='moves',
            field=models.IntegerField(default=0),
        ),
    ]
