# Generated by Django 4.1.6 on 2023-06-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0013_chessgame_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgamestatistics',
            name='highest_elo_rating',
            field=models.IntegerField(default=0),
        ),
    ]
