# Generated by Django 4.1.6 on 2023-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_', '0014_chessgamestatistics_highest_elo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='turn',
            field=models.CharField(default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='chessgamestatistics',
            name='elo_rating',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='chessgamestatistics',
            name='highest_elo_rating',
            field=models.IntegerField(default=500),
        ),
    ]
